### ISSUE TITLE
How to generate server stub and skip Controller/Impl generation?

### ISSUE THREAD

**Issue by simonlinj** [int128/gradle-swagger-generator-plugin#122]
I want to generate my spring server stub from a yaml into `build/swagger-code-petstore` then I can write my own Controller/Implementation in src/main/java/explame.api

But I'm unable to skip the PetApiController generation. Tried this, but still generating all ApiController's files
```
  "additionalProperties": {
    "ignore-file-override": ".swagger-codegen-ignore"
  }
```

.swagger-codegen-ignore
```
*ApiController.java
```

Am I missing something?  or if there is any workaround?

**Comment by int128** [comment]
Would you try the following option?

```groovy
swaggerSources {
  petstore {
    code {
      rawOptions = ["--ignore-file-override=.swagger-codegen-ignore"]
    }
  }
}
```

**Comment by simonlinj** [comment]
arigatou gozaimasu @int128 !

**Comment by rtfpessoa** [comment]
@int128 Just tried this workaround but got an error.

Is there a better way to do this? Or What might be causing this?

```
[main] ERROR io.swagger.parser.util.DeserializationUtils - Error snake-parsing yaml content
io.swagger.parser.util.DeserializationUtils$SnakeException: Exception safe-checking yaml content  (maxDepth 2000)
        at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:300)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:369)
        at io.swagger.parser.util.DeserializationUtils.readYamlTree(DeserializationUtils.java:137)
        at io.swagger.parser.Swagger20Parser.deserializeYaml(Swagger20Parser.java:83)
        at io.swagger.parser.Swagger20Parser.convertToSwagger(Swagger20Parser.java:125)
        at io.swagger.parser.Swagger20Parser.read(Swagger20Parser.java:109)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:69)
        at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:431)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:283)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.IllegalAccessError: tried to access field org.yaml.snakeyaml.constructor.BaseConstructor.composer from class io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor
        at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:279)
        ... 10 more
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'CommitFile'
        at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:425)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:751)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.NullPointerException
        at io.swagger.codegen.ignore.CodegenIgnoreProcessor.allowsFile(CodegenIgnoreProcessor.java:111)
        at io.swagger.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:765)
        at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:412)
        ... 3 more
```

Using config `build.gradle.kts`:
```
swaggerSources {
    create("example") {
        setInputFile(file("swagger.yaml"))
        code.language = "spring"
        code.configFile = file("swagger-codegen-config.json")
        code.dependsOn(validation)
        code.components = setOf("models", "apis")
        code.rawOptions = listOf("--ignore-file-override=.swagger-codegen-ignore")
    }
}
```

**Comment by rtfpessoa** [comment]
Seems like it was related to the relative path in the parameter. Absolute path fixed it.
The error is misleading.
