### ISSUE TITLE
Can't generate SwaggerUI with plugin version 2.19.2

### ISSUE THREAD

**Issue by chkpnt** [int128/gradle-swagger-generator-plugin#298]
## Describe the bug
I'm getting the following `NoSuchMethodError` error, when executing `generateSwaggerUI`:

```
Caused by: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.io.ContentReference com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createContentReference(java.lang.Object)'
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:353)
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3076)
	at com.fasterxml.jackson.databind.ObjectMapper$readTree$0.call(Unknown Source)
	at org.hidetake.gradle.swagger.generator.GenerateSwaggerUI.buildSwaggerSpec(GenerateSwaggerUI.groovy:85)
	at org.hidetake.gradle.swagger.generator.GenerateSwaggerUI.exec(GenerateSwaggerUI.groovy:64)
	...
```

But honestly, I can't explain it: The referenced method has been introduced in `jackson-core` 2.13 (https://github.com/FasterXML/jackson-core/blob/2.13/src/main/java/com/fasterxml/jackson/core/JsonFactory.java#L1987), and `com.fasterxml.jackson.core:jackson-core:2.13.1` is on the classpath:

```
> ./gradlew buildEnvironment
[...]
classpath
\--- org.hidetake.swagger.generator:org.hidetake.swagger.generator.gradle.plugin:2.19.2
     \--- gradle.plugin.org.hidetake:gradle-swagger-generator-plugin:2.19.2
          +--- com.github.java-json-tools:json-schema-validator:2.2.14
          |    +--- com.google.guava:guava:28.2-android
          |    |    +--- com.google.guava:failureaccess:1.0.1
          |    |    +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
          |    |    +--- com.google.code.findbugs:jsr305:3.0.2
          |    |    +--- org.checkerframework:checker-compat-qual:2.5.5
          |    |    +--- com.google.errorprone:error_prone_annotations:2.3.4
          |    |    \--- com.google.j2objc:j2objc-annotations:1.3
          |    +--- com.github.java-json-tools:jackson-coreutils-equivalence:1.0
          |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.11.0 -> 2.13.1
          |    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.13.1
          |    |    |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.1
          |    |    |    |         +--- com.fasterxml.jackson.core:jackson-annotations:2.13.1 (c)
          |    |    |    |         +--- com.fasterxml.jackson.core:jackson-core:2.13.1 (c)
          |    |    |    |         +--- com.fasterxml.jackson.core:jackson-databind:2.13.1 (c)
          |    |    |    |         \--- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.13.1 (c)
          |    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.13.1
          |    |    |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.1 (*)
          |    |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.1 (*)
          |    |    +--- com.google.guava:guava:28.2-android (*)
          |    |    \--- com.github.java-json-tools:jackson-coreutils:2.0
          |    |         +--- com.fasterxml.jackson.core:jackson-databind:2.11.0 -> 2.13.1 (*)
          |    |         +--- com.github.java-json-tools:msg-simple:1.2
          |    |         |    +--- com.github.java-json-tools:btf:1.3
          |    |         |    |    \--- com.google.code.findbugs:jsr305:2.0.1 -> 3.0.2
          |    |         |    \--- com.google.code.findbugs:jsr305:2.0.1 -> 3.0.2
          |    |         \--- com.google.code.findbugs:jsr305:3.0.2
          |    +--- com.github.java-json-tools:json-schema-core:1.2.14
          |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.11.0 -> 2.13.1 (*)
          |    |    +--- com.google.guava:guava:28.2-android (*)
          |    |    +--- com.github.java-json-tools:jackson-coreutils:2.0 (*)
          |    |    +--- com.github.java-json-tools:jackson-coreutils-equivalence:1.0 (*)
          |    |    +--- com.github.java-json-tools:uri-template:0.10
          |    |    |    +--- com.google.guava:guava:28.1-android -> 28.2-android (*)
          |    |    |    +--- com.github.java-json-tools:msg-simple:1.2 (*)
          |    |    |    \--- com.google.code.findbugs:jsr305:2.0.1 -> 3.0.2
          |    |    +--- org.mozilla:rhino:1.7.7.2
          |    |    \--- com.google.code.findbugs:jsr305:3.0.2
          |    +--- com.sun.mail:mailapi:1.6.2
          |    +--- joda-time:joda-time:2.10.5
          |    +--- com.googlecode.libphonenumber:libphonenumber:8.11.1
          |    +--- com.google.code.findbugs:jsr305:3.0.2
          |    \--- net.sf.jopt-simple:jopt-simple:5.0.4
          +--- com.fasterxml.jackson.core:jackson-databind:2.13.1 (*)
          \--- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.13.1
               +--- com.fasterxml.jackson.core:jackson-databind:2.13.1 (*)
               +--- org.yaml:snakeyaml:1.28
               +--- com.fasterxml.jackson.core:jackson-core:2.13.1 (*)
               \--- com.fasterxml.jackson:jackson-bom:2.13.1 (*)
```

To Reproduce:

`./gradlew generateSwaggerUI`

Expected behavior:

Swagger-UI is generated.

## Environment
Plugin version: 2.19.2
Swagger Codegen version: 3.0.32
Gradle version: 7.3.3
Java version: 11
OS: macOS 11.6.2

**Comment by xtina** [comment]
I too ran into this issue and fixed it by adding `classpath 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.13.2'` to my dependencies.

**Comment by chkpnt** [comment]
This issue seems to be resolved! I've just disabled my workaround, which have been

```groovy
buildscript {
    dependencies {
        classpath "gradle.plugin.org.hidetake:gradle-swagger-generator-plugin:2.19.2"
        
        // Workaround for https://github.com/int128/gradle-swagger-generator-plugin/issues/298
        classpath("com.github.fge:json-schema-validator") {
            version {
                strictly '2.2.6'
            }
        }
        classpath("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml") {
            version {
                strictly '2.2.3'
            }
        }
    }
}
```

and I can't reproduce the issue.

These are the dependencies I'm using now:

```groovy
dependencies {
    swaggerUI "org.webjars:swagger-ui:4.14.3"
    swaggerCodegen 'io.swagger.codegen.v3:swagger-codegen-cli:3.0.35'
    swaggerTemplate 'io.swagger.codegen.v3:swagger-codegen-generators:1.0.35'
    implementation 'io.swagger.core.v3:swagger-annotations:2.2.4'
}
```
