### ISSUE TITLE
Open API 3.0

### ISSUE THREAD

**Issue by kevcodez** [int128/gradle-swagger-generator-plugin#86]
Does the plugin support pOpen API 3.0?

I tried using the petstore example and the validation fails.

**Comment by int128** [comment]
At this time the JSON schema of OpenAPI 3.0 is not available yet (https://github.com/OAI/OpenAPI-Specification/issues/1032). Please skip the validation.

Other tools seem:

- [Code generation](https://github.com/swagger-api/swagger-codegen): Supported in 3.0 (currently snapshot version)
- [Swagger UI](https://github.com/swagger-api/swagger-ui): Supported in 3.12
- ReDoc: Not yet (https://github.com/Rebilly/ReDoc/issues/312)

**Comment by kevcodez** [comment]
Is the plugin able to generate code when skipping the validation for OpenAPI 3.0?

**Comment by int128** [comment]
Yes. Just run the `generateSwaggerCode` task.

Sorry I have tested code generation with the latest snapshot version of `swagger-codegen-cli` but it does not work for now.

**Comment by darrelmiller** [comment]
Just an FYI, the JSON Schema will not be able to completely validate an OpenAPI document.  It can partially validate it, but if you need a valid OpenAPI description you should not rely on JSON Schema.

**Comment by motorro** [comment]
I've used jitpack to get plugin working:
```groovy
dependencies {
    swaggerCodegen 'com.github.swagger-api:swagger-codegen:b5c8b2162f5f34ff8db10c87461ea6e8aa066f76'
}
```
That was the commit I've used to test when submitting a feature to generators.
Also tried to substitute a generators module but failed (1.0.0-SNAPSHOT templates still used). 
```groovy
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'io.swagger' && details.requested.name == 'swagger-codegen-generators' && details.requested.version == '1.0.0-SNAPSHOT') {
            details.useTarget "com.github.swagger-api:swagger-codegen-generators:772f1c3e8b9efc7d7220c96067870471895054cb"
        }
    }
}
```
Although `dependencies` display a correct substitution...
Anyway, works for me now as I need only model at the moment

**Comment by krisztiankocsis** [comment]
Hi!
Can't use the new V3 generator because it is moved to a newer package.

Caused by: java.lang.IllegalStateException: Add swagger-codegen-cli to dependencies of the project as follows:
  dependencies {
    swaggerCodegen 'io.swagger:swagger-codegen-cli:x.x.x'
  }
...
Caused by: java.lang.ClassNotFoundException: io.swagger.codegen.SwaggerCodegen

It is now:
io.swagger.codegen.v3:swagger-codegen-cli:3.0.0

When can we expect support for this one?

**Comment by int128** [comment]
Yes, the new 3.x line will be supported in the near future.

**Comment by int128** [comment]
I have released 2.14.0 and now it supports Swagger Codegen V3.
https://github.com/int128/gradle-swagger-generator-plugin/releases/tag/2.14.0

Note that it does not yet support OpenAPI 3 YAML validation.

**Comment by lorenet** [comment]
> 
> 
> I have released 2.14.0 and now it supports Swagger Codegen V3.
> https://github.com/int128/gradle-swagger-generator-plugin/releases/tag/2.14.0
> 
> Note that it does not yet support OpenAPI 3 YAML validation.

Hi!
I'm using version 2.16.0 and Swagger Codegen V3 doesn't seem to support Server Templating:

16:56:54.780 [Thread-388] WARN io.swagger.codegen.v3.utils.URLPathUtil - Not valid URL: https://test.api.com:{port}/{basePath}
java.net.MalformedURLException: For input string: "{port}"
        at java.net.URL.<init>(URL.java:627)
        at java.net.URL.<init>(URL.java:490)
        at java.net.URL.<init>(URL.java:439)
        at io.swagger.codegen.v3.utils.URLPathUtil.getServerURL(URLPathUtil.java:30)
        at io.swagger.codegen.v3.generators.java.SpringCodegen.preprocessOpenAPI(SpringCodegen.java:428)
        at io.swagger.codegen.v3.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:193)
        at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:714)
        at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:330)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NumberFormatException: For input string: "{port}"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:222)
        at java.net.URL.<init>(URL.java:622)
        ... 8 common frames omitted

**Comment by sdelamo** [comment]
It would be great to get Open API v3 validation.

**Comment by t2y** [comment]
I am using 2.18.1 version. The validateSwaggerOpenapi task is failed when it validates openapi.yaml (3.0.2).
